version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ${DATA_VOLUME_PATH}:/app # Use an environment variable
    container_name: web-dev-course_web
    restart: unless-stopped
